---
title: "Spatial translator"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    horizontal_layout: scroll
    theme: spacelab
    navbar:
      - { title: "reproducible.co.nz", href: "https://reproducible.co.nz", align: right }
    source_code: embed 
    orientation: columns
---
<style>

body {
  padding-top: 70px;
}


.navbar-brand {
font-family: "Candara";
  font-weight: bold;
  font-size: 24px;
}


</style>


```{r}
library(sf)
library(flexdashboard)
library(shiny)
library(tidyverse)
library(curl)
library(lubridate)
library(shinyFiles)
library(DT)
library(zip)
```

Conversion
=============================================


Column {.sidebar data-width=380}
-------------------------------------

Select transformation with **From** & **To**. Upload file. Fill and check widgets. Click **Update** when happy. Check input and output then **Download**.

<br/>

```{r}
# Input From 
  selectInput("from", label = HTML("<b>FROM</b>"), 
    choices = c("csv", "gpx", "kml", "shp (zipped)")
    )
```


```{r}
# read files; somewhat complex for shapefiles
dataset <- eventReactive(input$file_from,{
  
  if(input$from != "shp (zipped)"){
    
  dataset <- st_read(input$file_from$datapath, quiet = TRUE)
  dataset
  
  } else {
    
  # Create temp files
  zipped <- input$file_from$datapath
  unzipped <- tempfile()
  
  # Unzip the contents of the temp and save unzipped content in 'temp2'
  unzip(zipfile = zipped, exdir = unzipped)

  # Define the shapefile path
  shapefile_path <- file.path(unzipped)
  
  dataset <- st_read(shapefile_path, quiet = TRUE)
  dataset
  
  }
    

})
```


<br/>

```{r}

# Input To
renderUI({
  
  old.choices <-  c("csv", "gpx", "kml", "shp (zipped)")
  new.choices <- old.choices[old.choices != input$from]
  
  selectInput("to", label = HTML("<b>TO</b>"), 
    choices = new.choices)
  
  
})
```

<br/>

```{r, echo = FALSE}
# reactive upload widget

renderUI({
  
  if (input$from == "gpx"){
    
    fileInput("file_from", HTML("<b>Choose gpx file</b>"),
                    multiple = FALSE)
    
  } else if (input$from  == "csv"){
  
    fileInput("file_from", HTML("<b>Choose csv file</b> <br/>(missing coords will be dropped)"),
                    multiple = FALSE)
  
  } else if (input$from  == "shp (zipped)"){
  
    fileInput("file_from", HTML("<b>Choose shp files (zipped)</b>"),
                    multiple = FALSE)
  
  } else {
    
    fileInput("file_from", HTML("<b>Choose kml file</b>"),
                    multiple = FALSE)
    
  }
  
  
})

```

<br/>



```{r}
# input CRS for csv only
renderUI({
  if (input$from == "csv") {
    # latitude
    numericInput("input.crs",
                label = HTML("<b>Input coordinate ref system (epsg)</b><br/>longlat is default (4326)"),
                value = 4326)
    
  }
  
})
```

<br/>


```{r}
# select longitude column (from csv only)
renderUI({
  if (input$from == "csv") {
    # latitude
    selectInput("longitude",
                label = HTML("<b>Select longitude column</b>"),
                choices = sort(unique(names(dataset(
                )))))
    
  }
  
})
```

<br/>

```{r}
# select latitude column (from csv only)

renderUI({
  if (input$from == "csv") {
    # latitude
    selectInput("latitude",
                label = HTML("<b>Select latitude column</b>"),
                choices = sort(unique(names(dataset(
                )))))
  }
  
})
```

<br/>

```{r}
# Output CRS widget
numericInput(
  "output.crs",
  label = HTML(
    "<b>Output coordinate ref system (epsg)</b><br/>longlat is default (4326)"
  ),
  value = 4326
)

```

<br/>

```{r}
# update button
actionButton("update", "Click to update", class = "btn-warning")
```

<br/>

```{r}
# Create placeholder for the downloadButton
uiOutput("downloadUI")
```

```{r, echo = FALSE}
# download handler
# note that gpx and shp formats require special handling
output$downloadUI <- renderUI( {
  downloadButton("downBtn", "Download data", style = "width:100%;")
})

 output$downBtn <- downloadHandler(
    filename = function() {
      paste0("Name_your_file.",
             if (input$to != "shp (zipped)") {
               input$to
             } else {
               "zip"
             }
      )
    },
    content = function(file) {
      if (input$to == "gpx") {
        st_write(final(), file, driver = "GPX", waypoints = TRUE, dataset_options = "GPX_USE_EXTENSIONS=YES")
        
    } else if (input$to == "shp (zipped)" ) {
      
      # clear temporary files
      unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
      
      # create temporary directory
      temp_dir <-  tempdir()
      
      # make paths
      name.base <- file.path(temp_dir, "Name this file")
      name.glob <- paste0(name.base, ".*")
      name.shp  <- paste0(name.base, ".shp")
      name.zip  <- paste0(name.base, ".zip")
      
      # write to sf
      st_write(final(), dsn = name.shp,  driver = "ESRI Shapefile")
      
      # zip file
      zipr(zipfile = name.zip, files = Sys.glob(name.glob))
    
      # copy the zip file to the file argument
      file.copy(name.zip, file)
        
      # remove all the files created
      if (length(Sys.glob(name.glob)) > 0) file.remove(Sys.glob(name.glob))
      
      
      } else {
        st_write(final(), file)
      }
    }
  )
  

    
```

<br/>
<br/>

Column {.tabset}
-------------------------------------
### Input

```{r}
# show input metadata

their.input <- eventReactive(input$update, {
  
  
  if(input$from != "csv"){
  my.list <- list(Format_from = input$from,
                  Format_to = input$to,
                  CRS = dataset() %>% st_crs(),
                  Extent = dataset() %>% st_bbox(),
                  Variables = names(dataset())
  )
  
  } else {
    
  my.list <- list(Format_from = input$from,
                  Format_to = input$to,
                  Longitude = input$longitude,
                  Latitude = input$latitude,
                  Variables = names(dataset())
  )
    
  }
  
  print(my.list)
  
})


renderPrint({
  
  their.input()
})
```




### Output

```{r}


final <- reactive({
  
  if(input$to == "csv"){
    
    dataset <- dataset() %>% st_transform(crs = input$output.crs)
    
     # get CRS code
    # Get the CRS information
    crs_info <- st_crs(dataset)
    
      
    coord <- st_coordinates(dataset)
    st_geometry(dataset) <- NULL
      
    df <- cbind(dataset, coord) %>% as.data.frame()
    
    # as coord as X and Y we must rename
    df <- df %>% rename (latitude =Y,
                  longitude = X)
    
    # move to first columns for easy reading
    df %>% relocate(latitude) %>% relocate(longitude)
    
    # record CRS info as espg number
    df$CRS.epsg <- crs_info$epsg
    
    df
    
  } else if (input$from == "csv") {
    
    dataset <- dataset()
    
    # drop if NA note use of base R alternate
    dataset <- dataset[dataset[,input$longitude] != "",]
    dataset <- dataset[dataset[,input$latitude] != "",]
   
    
    # change to sf
    spatial <- st_as_sf(dataset,
                        coords = c(input$longitude, input$latitude), 
                        crs = input$input.crs) %>% 
      st_transform(crs = input$output.crs)
    
    spatial 
    
  } else {
    
     dataset <- dataset() %>% st_transform(crs = input$output.crs)
     dataset
    
}
  
    
})
```

```{r}
# show output metadata

their.output <- eventReactive(input$update, {
  
   
  if(input$to != "csv"){
  my.list <- list(Format_from = input$from,
                  Format_to = input$to,
                  CRS = final() %>% st_crs(),
                  Extent = final() %>% st_bbox(),
                  Variables = names(final())
  )
  
  } else {
    
  my.list <- list(Format_from = input$from,
                  Format_to = input$to,
                  CRS = input$output.crs,
                  Longitude = input$longitude,
                  Latitude = input$latitude,
                  Variables = names(final())
  )
    
  }
  
  print(my.list)
  

})

renderPrint({
  
  their.output()
  
})
```





Help & videos
=============================================


Column {.sidebar data-width=350}
-------------------------------------

**Coordinate reference systems**

A searchable registry of the epsg coordinate reference system can be found [here](https://epsg.io/).

<br/>

**References**

The spatial transformations used in this dashboard were implemented using the ['sf' package](https://cran.r-project.org/web/packages/sf/): 

*Edzer Pebesma and Roger Bivand and Sebastian Luque (2023). Spatial Data Science: With Applications in R. Chapman and Hall. CRC Press.*


<br/>

**Acknowledgements**

The code for this dashboard was written by Nathan Whitmore is freely available for reuse and modification via an [MIT license](https://choosealicense.com/licenses/mit/). The source code can be found under the under the '</> Source Code' tab or via [GitHub](https://github.com/NathanWhitmore/spatial_translator). 

Dashboard creation was funded by the Otago Regional Council. Special thanks go to Scott Jarvie for instigating this project.


Column 
-------------------------------------

### Help video

<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/fadfc39e7835425da1b3640a0cc47a5b?sid=3c7d95f7-d70f-4ba2-acf7-b09ed842776d" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 80%; height: 80%;"></iframe></div>
